### ISSUE TITLE
JSONDecodeError when running action

### ISSUE THREAD

**Issue by VincentRPS** [actions-rust-lang/audit#98]
When trying to build [branch 1](https://github.com/metallang/metal/tree/drill/init) and [branch 2](https://github.com/metallang/metal/tree/analyzer/init) the action gives a Python-originating JSONDecodeError. Along the lines of the following:

![image](https://github.com/user-attachments/assets/1261026f-4e4a-4e4d-b6c8-7a34eb4ec434)

Direct github actions results showing this same error can be found [here](https://github.com/metallang/metal/actions/runs/12155688392/job/34257167406) and [here](https://github.com/metallang/metal/actions/runs/12338090479/job/34432616464).

**Comment by jonasbb** [comment]
Running `cargo audit` fails in the repository, since there is no `Cargo.lock` and generating the `Cargo.lock` requires an unstable Rust version, mainly due to the `edition2024` usage in some crates. This action just runs `cargo audit` with the default installed Rust version, which is Rust stable on the GitHub runners.

To fix this, you can either add the `Cargo.lock` to the repository, generate it before invoking this action, or change the default Rust version to nightly, for example using https://github.com/actions-rust-lang/setup-rust-toolchain.

The way this currently fails is definitely suboptimal and I try to pass through the original error message, instead of just showing a JSON decode error.
